### ISSUE TITLE
HOW THE HELL A RAW SQL SHOULD BE EXECUTED.....

### ISSUE THREAD

**Issue by gnanakeethan** [rawphp-framework/rawphp#3]
................... ETTT???

**Comment by davepartner** [comment]
It is easy, see this => https://laravel.com/docs/5.5/database#running-queries

**Comment by davepartner** [comment]
Thanks for raising this issue, this has now been resolved.

**Comment by gnanakeethan** [comment]
I am a laravel guy for 4 years and I never understood the gains of this project. 

The above link doesn’t give solution as FACADE is not configured

**Comment by davepartner** [comment]
It should work seamlessly, have you tried it? You need to import laravel in your model (this should be there by default), then import your model into your controller. Please read the 'getting started' guide on RawPHP docs.
